/** Hands generated bytes to the browser as a file download, releasing the URL after. */
export function downloadFile(
  fileName: string,
  mimeType: string,
  content: string | Uint8Array,
): void {
  const url = URL.createObjectURL(new Blob([content as BlobPart], { type: mimeType }))
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  link.rel = 'noopener'
  document.body.append(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}
