/**
 * Re-copies the two standalone rental portals into the superapp.
 *
 * apps/admin-portal and apps/owner-portal remain the editable source of truth
 * and the deployment rollback path. apps/web/src/modules/rental holds derived
 * copies of both. Edit a portal, run this, push once — otherwise the superapp
 * silently keeps serving the old screens.
 *
 * Everything under apps/web/src/modules/rental/{admin,owner} is REGENERATED.
 * Never hand-edit those trees; change the portal and re-run.
 *
 * Usage: node scripts/sync-rental.mjs [--check]
 *   --check  report drift and exit non-zero without writing (for CI)
 */
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('../', import.meta.url))
const CHECK = process.argv.includes('--check')

const TREES = [
  {
    name: 'admin',
    from: 'apps/admin-portal/src',
    to: 'apps/web/src/modules/rental/admin',
    alias: '@rental-admin',
    // Entry points and sign-in belong to the superapp, not the module.
    drop: ['main.tsx', 'index.css', 'vite-env.d.ts', 'routes/login-page.tsx'],
  },
  {
    name: 'owner',
    from: 'apps/owner-portal/src',
    to: 'apps/web/src/modules/rental/owner',
    alias: '@rental-owner',
    drop: ['main.tsx', 'index.css', 'vite-env.d.ts', 'App.tsx', 'routes/login.tsx'],
  },
]

const PREFIX = '/app/rental'

/** The superapp owns one client and one cache; two of either breaks auth/invalidation. */
const SINGLETONS = {
  'lib/supabase.ts': `/**
 * Repointed at the superapp singleton. Two clients would mean two auth
 * sessions racing each other's token refresh.
 *
 * GENERATED by scripts/sync-rental.mjs — do not edit.
 */
export { supabase } from '@/lib/supabase'
`,
  'lib/query-client.ts': `/**
 * Repointed at the superapp singleton. A second QueryClient would mean
 * mutations invalidating a cache nobody reads from.
 *
 * GENERATED by scripts/sync-rental.mjs — do not edit.
 */
export { queryClient } from '@/lib/query-client'
`,
}

/**
 * Route tables are rewritten rather than patched: mounted behind the
 * /app/rental/* splat every `path` must be RELATIVE, and neither tree carries
 * a login screen any more.
 */
const ROUTE_FILES = {
  admin: {
    path: 'routes/index.tsx',
    // Derived from the portal's own route table; keep in step when routes change.
    contents: null, // filled in below
  },
  owner: { path: 'routes/index.tsx', contents: null },
}

function walk(dir, base = dir) {
  const out = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) out.push(...walk(full, base))
    else out.push(relative(base, full))
  }
  return out
}

/**
 * Rewrites a portal file for life inside the superapp:
 *  - `@/` becomes the module's own alias so it never collides with the superapp
 *  - absolute in-app links gain the /app/rental prefix, because navItemForPath,
 *    canAccessRoute and homeRouteForRole all match against real pathnames
 *  - /login is handed back to the superapp
 */
function transform(source, alias) {
  let s = source
  s = s.replaceAll("'@/", `'${alias}/`).replaceAll('"@/', `"${alias}/`)
  s = s
    .replaceAll('to="/', `to="${PREFIX}/`)
    .replaceAll('to={`/', `to={\`${PREFIX}/`)
    .replaceAll("navigate('/", `navigate('${PREFIX}/`)
    .replaceAll('navigate(`/', `navigate(\`${PREFIX}/`)
    .replaceAll("to: '/", `to: '${PREFIX}/`)
  s = s.replaceAll(`${PREFIX}/login`, '/login')
  return s
}

// ── Route tables ─────────────────────────────────────────────────────────────
ROUTE_FILES.admin.contents = `import { Navigate, Route, Routes } from 'react-router-dom'
import { ProtectedRoute } from '@rental-admin/auth/protected-route'
import { AppShell } from '@rental-admin/components/layout/app-shell'
import { AllotmentsPage } from './allotments-page'
import { AuditPage } from './audit-page'
import { BillingPage } from './billing-page'
import { BuildingsPage } from './buildings-page'
import { ComplaintsPage } from './complaints-page'
import { DashboardPage } from './dashboard-page'
import { DocumentsPage } from './documents-page'
import { ExpensesPage } from './expenses-page'
import { OwnersPage } from './owners-page'
import { PaymentsPage } from './payments-page'
import { ProfilePage } from './profile-page'
import { SettingsPage } from './settings-page'
import { StaffPage } from './staff-page'
import { TenantDetailPage } from './tenant-detail-page'
import { UnitsPage } from './units-page'

/**
 * GENERATED by scripts/sync-rental.mjs — do not edit.
 *
 * Mounted behind the superapp's \`/app/rental/*\` splat, so every \`path\` here is
 * RELATIVE. Sign-in is the superapp's. Absolute \`to=\` targets stay fully
 * qualified because navItemForPath/canAccessRoute match real pathnames.
 */
export function AppRoutes() {
  return (
    <Routes>
      <Route element={<ProtectedRoute />}>
        <Route element={<AppShell />}>
          <Route path="dashboard" element={<DashboardPage />} />
          <Route path="buildings" element={<BuildingsPage />} />
          <Route path="units" element={<UnitsPage />} />
          <Route path="allotments" element={<AllotmentsPage />} />
          <Route path="tenants" element={<OwnersPage />} />
          <Route path="tenants/:ownerId" element={<TenantDetailPage />} />
          <Route path="owners" element={<Navigate to="${PREFIX}/tenants" replace />} />
          <Route path="staff" element={<StaffPage />} />
          <Route path="complaints" element={<ComplaintsPage />} />
          <Route path="billing" element={<BillingPage />} />
          <Route path="expenses" element={<ExpensesPage />} />
          <Route path="payments" element={<PaymentsPage />} />
          <Route path="documents" element={<DocumentsPage />} />
          <Route path="audit" element={<AuditPage />} />
          <Route path="settings" element={<SettingsPage />} />
          <Route path="profile" element={<ProfilePage />} />
        </Route>
      </Route>
      <Route path="*" element={<Navigate to="${PREFIX}/dashboard" replace />} />
    </Routes>
  )
}
`

ROUTE_FILES.owner.contents = `import { Navigate, Route, Routes } from 'react-router-dom'

import { ProtectedRoute } from '@rental-owner/auth/protected-route'
import { AppShell } from '@rental-owner/components/app-shell'
import { ComplaintsScreen } from './complaints'
import { DocumentsScreen } from './documents'
import { HomeScreen } from './home'
import { InvoicesScreen } from './invoices'
import { LeaseScreen } from './lease'
import { ProfileScreen } from './profile'
import { ReceiptsScreen } from './receipts'
import { RemindersScreen } from './reminders'

/**
 * GENERATED by scripts/sync-rental.mjs — do not edit.
 *
 * The owner tree's routes, lifted out of the portal's App.tsx. The superapp
 * owns the router, the QueryClientProvider and the Toaster; this contributes
 * only the route table. Paths are RELATIVE to the /app/rental/* splat.
 */
export function OwnerRoutes() {
  return (
    <Routes>
      <Route element={<ProtectedRoute />}>
        <Route element={<AppShell />}>
          <Route path="home" element={<HomeScreen />} />
          <Route path="lease" element={<LeaseScreen />} />
          <Route path="invoices" element={<InvoicesScreen />} />
          <Route path="reminders" element={<RemindersScreen />} />
          <Route path="receipts" element={<ReceiptsScreen />} />
          <Route path="complaints" element={<ComplaintsScreen />} />
          <Route path="documents" element={<DocumentsScreen />} />
          <Route path="profile" element={<ProfileScreen />} />
        </Route>
      </Route>
      <Route path="*" element={<Navigate to="${PREFIX}/home" replace />} />
    </Routes>
  )
}
`

// ── Build each tree in memory, then compare or write ─────────────────────────
let drift = 0

for (const tree of TREES) {
  const fromDir = join(ROOT, tree.from)
  if (!existsSync(fromDir)) {
    console.error(`missing source: ${tree.from}`)
    process.exit(1)
  }

  const built = new Map()
  for (const rel of walk(fromDir)) {
    if (tree.drop.includes(rel.split('\\').join('/'))) continue
    const full = join(fromDir, rel)
    if (/\.(ts|tsx)$/.test(rel)) built.set(rel, transform(readFileSync(full, 'utf8'), tree.alias))
    else built.set(rel, readFileSync(full))
  }
  for (const [rel, contents] of Object.entries(SINGLETONS)) built.set(rel, contents)
  built.set(ROUTE_FILES[tree.name].path, ROUTE_FILES[tree.name].contents)

  const toDir = join(ROOT, tree.to)

  if (CHECK) {
    const existing = existsSync(toDir) ? new Set(walk(toDir)) : new Set()
    for (const [rel, contents] of built) {
      const target = join(toDir, rel)
      const current = existsSync(target) ? readFileSync(target) : null
      const want = Buffer.isBuffer(contents) ? contents : Buffer.from(contents)
      if (current === null || !current.equals(want)) {
        console.log(`  drift: ${tree.to}/${rel}`)
        drift++
      }
      existing.delete(rel)
    }
    for (const rel of existing) {
      console.log(`  stale: ${tree.to}/${rel}`)
      drift++
    }
    continue
  }

  rmSync(toDir, { recursive: true, force: true })
  for (const [rel, contents] of built) {
    const target = join(toDir, rel)
    mkdirSync(join(target, '..'), { recursive: true })
    writeFileSync(target, contents)
  }
  console.log(`  ${tree.to}: ${built.size} files`)
}

if (CHECK) {
  if (drift) {
    console.error(`\n${drift} file(s) out of sync. Run: node scripts/sync-rental.mjs`)
    process.exit(1)
  }
  console.log('rental module is in sync')
} else {
  console.log('\nSynced. Now run: pnpm typecheck')
}
