/**
 * Repointed at the superapp singleton. A second QueryClient would mean
 * mutations invalidating a cache nobody reads from.
 *
 * GENERATED by scripts/sync-rental.mjs — do not edit.
 */
export { queryClient } from '@/lib/query-client'
