/**
 * Repointed at the superapp singleton. Two clients would mean two auth
 * sessions racing each other's token refresh.
 *
 * GENERATED by scripts/sync-rental.mjs — do not edit.
 */
export { supabase } from '@/lib/supabase'
