-- Migration: create private Supabase Storage buckets
-- Task 12.2
-- Requirements 13.1
-- Buckets are private (public = false); all access is via signed URLs / the SDK
-- under Storage RLS. file_size_limit is a coarse hard ceiling set to the largest
-- value an Administrator could ever configure — the per-request, per-type check in
-- file_storage_config (Requirement 13.4) is the real gate, enforced server-side in
-- the upload Edge Functions. Object keys are UUID-based, generated by those
-- functions, never derived from user-supplied file names.

insert into storage.buckets (id, name, public, file_size_limit)
values
  ('complaint-attachments', 'complaint-attachments', false, 10485760),
  ('owner-documents', 'owner-documents', false, 52428800),
  ('receipts', 'receipts', false, 52428800)
on conflict (id) do nothing;
